---
- hosts: prod
  become: yes

  tasks:

    - name: Pull Docker Image
      shell: docker pull yourdockerhubusername/springboot-app:latest

    - name: Run Spring Boot Container
      shell: |
        docker run -it -d --name springboot-app --network spring-network -p 8085:8085 divya2057/springboot-app