services:
    app:
       build: .
       image: employee
       container_name: crud
       environment:
          SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/emp?createDatabaseIfNotExist=true
          SPRING_DATASOURCE_USERNAME=root
          SPRING_DATASOURCE_PASSWORD=root
       depends_on:
         - db 
       ports:
         - "8081:2030" 
       restart: always
       networks:
        - spring-network
       
    db:
      image: mysql:8
      container_name: springboot-db
      restart: always
      ports:
        - "3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD=root
        MYSQL_DATABASE=emp
      volumes:
        - mysql_data:/var/lib/mysql 
      networks:
       - spring-network
volumes:
    mysql_data:    

networks:
   spring-network:           
