---
- name: remove app
  hosts: prod
  user: ansible
  becomes: yes
  connection: ssh
  tasks: 
    - name: stop app container
      shell : docker stop app || true
      
    - name: remove app conainer
      shell: docker rm app || true